Update static.yml

diff --git a/.github/workflows/static.yml b/.github/workflows/static.yml
--- a/.github/workflows/static.yml
+++ b/.github/workflows/static.yml
@@ -1,24 +1,58 @@
-# GitHub Action: Push git subdirectory as branch
-# Source: https://github.com/marketplace/actions/push-git-subdirectory-as-branch
-
-name: Deploy to GitHub Pages
+# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
+# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
+# Workflow triggering derived from: https://stevenmortimer.com/running-github-actions-sequentially/
 on:
-  repository_dispatch:
-    types:
-      - trigger-renderbook-workflow
+  push:
+    branches: 
+    - master
+    paths:
+    - inst/examples
+    - '**.Rmd'
   workflow_dispatch:
 
-jobs:
-  deploy:
-    name: Deploy to GitHub Pages
-    runs-on: ubuntu-latest
-    steps:
-    - uses: actions/checkout@master
+name: renderbook
 
-    - name: Deploy
-      uses: s0/git-publish-subdir-action@develop
-      env:
-        REPO: self
-        BRANCH: gh-pages
-        FOLDER: inst/examples/_book
-        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+jobs:
+  render-book:
+    runs-on: ubuntu-latest
+    env:
+      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
+
+    steps:
+      - uses: actions/checkout@v2
+
+      - uses: r-lib/actions/setup-pandoc@v2
+
+      - uses: r-lib/actions/setup-r@v2
+        with:
+          use-public-rspm: true
+          
+    
+      - uses: r-lib/actions/setup-r-dependencies@v2
+        with:
+          needs: website
+          extra-packages:
+            any::devtools
+            local::.
+            
+      - name: install comhis
+        run: Rscript -e 'devtools::install_github("comhis/comhis",dependencies = TRUE)'
+     
+      - name: Render Book
+        run: Rscript -e 'bookdown::render_book("inst/examples/")'
+        
+      - name: Deploy package
+        run: |
+          git config --local user.name "$GITHUB_ACTOR"
+          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
+          git add .
+          git commit -m "Re-render bookdown documents" || echo "No changes to commit"
+          git push origin || echo "No changes to commit"
+      - name: Trigger pkgdown workflow
+        if: success()
+        uses: peter-evans/repository-dispatch@v1
+        with:
+          token: ${{ secrets.REPO_GHA_PAT }}
+          repository: ${{ github.repository }}
+          event-type: trigger-renderbook-workflow
+          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
